import { AuthProvider } from '@/contexts/AuthContext';
import { getServerSession } from '@/lib/getServerSession';
import type { Metadata } from 'next';
import { Creepster } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

const creepster = Creepster({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-creepster',
});

export const metadata: Metadata = {
  title: 'MELODY X MAKER',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const initialSession = await getServerSession();

  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${creepster.variable} absolute inset-0 antialiased`}
      >
        <AuthProvider initialSession={initialSession}>{children}</AuthProvider>
      </body>
    </html>
  );
}
